### ISSUE TITLE
Cant pass step 14

### ISSUE THREAD

**Issue by InsaneLuv** [NativeFunction/SC-CL#1]
When i trying to run Cmake in llvm_src dir i get ann error.

most likely im doing something wrong when compiling. could you retall step 14 in more detail?

**Comment by NativeFunction** [comment]
It might be an error with the newer cmake version, try to use version 3.11.0. 
Also, this video on building SC-CL might be of use ([video](https://www.youtube.com/watch?v=wJBFLPpwbpw)).

**Comment by InsaneLuv** [comment]
The first thing I encountered after compiling was the missing .dll file "zlib1.dll" - I download it from internet n it worked

When i just trying to compile not modificated freemode.c i get so many errors:
![image](https://user-images.githubusercontent.com/69699689/169551519-7e4d4dd9-7fb0-47a8-81c8-7b92cbca2129.png)

as I understand it, i need databases, where can I select or find them?

log from cmd:
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin>SC-CL.exe -platform=PC -target=GTAV -g freemode.c
> Starting SC-CL ALPHA 0.7.3.5 running Clang 6.0.0
> Error while trying to load a compilation database:
> Could not auto-detect compilation database for file "freemode.c"
> No compilation database found in C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin or any parent directory
> fixed-compilation-database: Error while opening fixed database: no such file or directory
> json-compilation-database: Error while opening JSON database: no such file or directory
> Running without flags.
> Compiling: C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:1:2: error: invalid preprocessing directive
> #region Local Var
>  ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:2:2: error: unknown type name 'var'
>         var uLocal_0 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:3:2: error: unknown type name 'var'
>         var uLocal_1 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:14:21: error: invalid digit 'f' in octal constant
>         float fLocal_12 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:15:21: error: invalid digit 'f' in octal constant
>         float fLocal_13 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:16:21: error: invalid digit 'f' in octal constant
>         float fLocal_14 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:17:2: error: unknown type name 'var'
>         var uLocal_15 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:18:2: error: unknown type name 'var'
>         var uLocal_16 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:20:2: error: unknown type name 'var'
>         var uLocal_18 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:21:2: error: unknown type name 'var'
>         var uLocal_19 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:22:20: error: use of undeclared identifier 'NULL'
>         char* sLocal_20 = NULL;
>                           ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:23:2: error: unknown type name 'var'
>         var uLocal_21 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:24:2: error: unknown type name 'var'
>         var uLocal_22 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:25:21: error: invalid digit 'f' in octal constant
>         float fLocal_23 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:26:21: error: invalid digit 'f' in octal constant
>         float fLocal_24 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:27:21: error: invalid digit 'f' in octal constant
>         float fLocal_25 = 0f;
>                            ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:28:2: error: unknown type name 'var'
>         var uLocal_26 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:29:2: error: unknown type name 'var'
>         var uLocal_27 = 0;
>         ^
> C:\Users\InsaneLuv\Desktop\compiler\llvm_src_bin\Debug\bin\freemode.c:30:21: error: invalid digit 'f' in octal constant
>         float fLocal_28 = 0f;
>                            ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> Warning: Function "func_21519" does not exist
> Assertion failed: false && "Function doesnt exist", file c:\users\insaneluv\desktop\compiler\llvm_src\tools\clang\tools\extra\sc-cl\include\clangparsing\helpers\script.cpp, line 62

**Comment by NativeFunction** [comment]
The decompiler that you are using to produce freemode.c does not produce valid C11. The keyword "var" does not exist in C, In C float literals must have a decimal like 0.0f or 0.f. Regions in C must use #pragma to be valid. As for NULL that is defined in [constants.h](https://github.com/NativeFunction/SC-CL/blob/master/bin/include/constants.h)

**Comment by InsaneLuv** [comment]
> 

so which ysc decompiler is suitable?
i use already decompiled scripts from here:
https://github.com/Sainan/GTA-V-Decompiled-Scripts

**Comment by NativeFunction** [comment]
To my knowledge, there is no decompiler that decompiles to C and uses valid syntax. SC-CL is meant for the creation of new scripts. As for editing and recompiling rockstars scripts, I would recommend using an ASM decompiler and recompiler.

**Comment by InsaneLuv** [comment]
> To my knowledge, there is no decompiler that decompiles to C and uses valid syntax. SC-CL is meant for the creation of new scripts. As for editing and recompiling rockstars scripts, I would recommend using an ASM decompiler and recompiler.

I bet there is no way for me, cause no any contents about this 
Ill be waiting for this editor/decompiler from you its in demand im sure
