### ISSUE TITLE
Where do I set the LLVM option? (Step 11)

### ISSUE THREAD

**Issue by KonstantinosTourtsakis** [NativeFunction/SC-CL#2]
Hello, 

I don't understand step 11. Where do I  have to set the LLVM option? Do I need to add a CMake entry? I'm sorry if I'm missing something obvious here (because it does seem like a simple step).  The [video guide](https://www.youtube.com/watch?v=wJBFLPpwbpw) didn't help much as that step was not part of the build process back then. I assume it is now outdated.

Also do I need to use an older version of Visual Studio? I'm currently using 2019.

Thanks in advance!
Constantine

**Comment by NativeFunction** [comment]
It should be inside CMake.

**Comment by KonstantinosTourtsakis** [comment]
> It should be inside CMake.

It doesn't seem to be anywhere in CMake. I'll try using version 3.11.0 as you're suggesting [here](https://github.com/NativeFunction/SC-CL/issues/1#issuecomment-1131928961). I'll let you know if I overcome this issue.

**Comment by KonstantinosTourtsakis** [comment]
LLVM_ENABLE_PROJECTS won't show up on CMake. Where is it supposed to show up? 
This is what I see on CMake right now (I also included the configuration window):

![CMake - LLVM_ENABLE_PROJECTS](https://cdn.discordapp.com/attachments/670730950715375636/1075163716024283136/cmake.JPG)

**Comment by KonstantinosTourtsakis** [comment]
> Do I need to add a CMake entry?

So that's what it was. There's more reference [here](https://llvm.org/docs/CMake.html).
