### ISSUE TITLE
natives missing for gta v console and using utf8

### ISSUE THREAD

**Issue by EROOTIIK** [NativeFunction/SC-CL#2]
SET_VEHICLE_ON_GROUND_PROPERLY (0xE14FDBA6) and GET_CURRENT_LANGUAGE (0x761BE00B) are not in natives32.h

extern _native bool SET_VEHICLE_ON_GROUND_PROPERLY(Vehicle vehicle)l
extern _native int GET_CURRENT_LANGUAGE()l

and VEHICLE_FREIGHTTRAILEr  in consts32.h should be VEHICLE_FREIGHTTRAILER

Also, is it possible for gta v to encode strings in utf8 and not in extended ascii and removing the warning for "illegal character encoding"? It would be useful for using special characters (for other languages). Thanks.

**Comment by EROOTIIK** [comment]
Also, is it possible for gta v to encode strings in utf8 and not in extended ascii? It would be useful for using special characters (for other languages). Thanks

**Comment by NativeFunction** [comment]
If you are talking about unicode then i don't think that's possible.
Special characters in GTA V are dependent upon the font and can be accessed either using hex like \x00 or alt key codes but only up to 255.
The "illegal character encoding" warning is internal from clang but can you give me an example?

**Comment by EROOTIIK** [comment]
GTA are actually using utf8 encoding, the compiler compiles strings in extended ascii, for example bytes for à should be C3 A0 and not E0 so it doesn't show the good character in game

**Comment by NativeFunction** [comment]
You can specify a string with utf8 encoding using the u8 prefix.
http://en.cppreference.com/w/c/language/string_literal

**Comment by EROOTIIK** [comment]
![image](https://user-images.githubusercontent.com/20160324/28236457-6dc94fd2-6927-11e7-8d7b-758aefd65a9f.png)
dosen't works for me

**Comment by NativeFunction** [comment]
What encoding are you using for submenus.h? Try converting it to UTF-8-BOM.

**Comment by EROOTIIK** [comment]
Oh didn't know that we can change this in the settings, after checking, every files was saved with extended ascii, I have changed this to utf8 with bom and it works fine thanks for helping.
