### ISSUE TITLE
RDR Compiler Issue. [Bug, Numerous Scripts, Same Result Over The Years]

### ISSUE THREAD

**Issue by CabooseSayzWTF** [NativeFunction/SC-CL#4]
Okay I really have no idea how to word this and it sound logical.
So this has been a issue ever since RDR support was added. I've had to work around it these last few years.
I never really use github. Anyways okay i'll explain the very best I can.

So sometime when making scripts, let's say our compiled size is 23kb.
Let's say I go back and add 1 line of code, a simple print, I compile and the new size is say 5kb.
Keep in mind there is 0 error in code when this happens. It can be the cleanest code you have ever seen.
Compiler shows it compiled fine, however our compiled size gets drastically cutdown and the script is basically corrupt at this point.
No matter what menu base this will eventually happen and has been happening for years. It's why we are so limited in what we can do in rdr.

I really don't know what the problem is. The only fix's I've came up with is legit delete as many strings as possible, shorten code as much as possible to the point code is on one line for alot of code sometimes. It's a real headache.
However there's a issue, I've even ran across the issue when removing every single int, bool, function that I literally didn't use and boom script cut majorly down on compile. I wish I knew how to explain this but I don't. I can only assume it's a issue with sc-cl directly or bare minimum a issue with compression but I heavily want to doubt that.

This issue has happened between me and few others. Me, xTheDevilRazedMe, ImFoxxyyy, JamesTwt, Homer. You may not know them( I know you know foxxyyy) but it's a issue and i've tried to pinpoint the issue and i've had a few people look into SC-CL and nobody can figure the issue out. So a answer of any kind would be appreciated because it has been nothing but a pain in the ass.

Discord is: caboosesayzwtf
feel free to reach out. I'm more active there.

**Comment by xTheDevilRazedMe** [comment]
I can confirm this. This has been a issue for a long time.

**Comment by NativeFunction** [comment]
Is there a source you can send that replicates this issue?

**Comment by CabooseSayzWTF** [comment]
> Is there a source you can send that replicates this issue?

Yes I made a "throw away garbage source" just for this. However add me on discord and I can send it your way . Also after 2 years also got Panah aka sockstress to see the issue as well and he also confirmed there's a major problem going on.
