### ISSUE TITLE
obfuscation

### ISSUE THREAD

**Issue by Vicodin10** [NativeFunction/SC-CL#4]
Is there any way obfuscation can be improved.
With a small menu I tried level 3 and froze. 
So I tried levels 2, 1, and strings only 
but It will cause for nothing to show or work besides the default draw base
when you open the menu.
Or is there another way to at least encrypt strings?

I understand it is experimental but is it something that can be looked into more?

**Comment by NativeFunction** [comment]
Obfuscation level 3 and above was originally made for GTA V PC so not much testing was done. String encryption should work unless it's an endian issue.

**Comment by Vicodin10** [comment]
Do you have Skype, if I may ask?

**Comment by NativeFunction** [comment]
It does sound like an endian issue. Can you send me the compiled script you are using? 
My skype is apiiintense.

**Comment by Vicodin10** [comment]
sure on skype
